[project]
name = "python-l1-brain-games2-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hexlet-code",
]
[tool.uv]
dev-dependencies = [
    "ruff>=0.8.0",
]

[tool.uv.sources]
hexlet-code = { path = "code" }
